Configure repo
thoth-station/thoth-github-action pull request #12
Opened 2022-05-10 18:57 UTC by mayaCostantini

2022-05-10 18:57 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **fridex** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @fridex` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fthoth-github-action).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/thoth-station/thoth-github-action/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["fridex"]} -->

2022-05-11 08:22 UTC, codificat reviewed
Adding some suggestions

2022-05-11 08:22 UTC, codificat commented on OWNERS_ALIASES
> +    - mayaCostantini
is this file actually used in this repo?

2022-05-11 08:22 UTC, codificat commented on OWNERS
> +  - mayacostantini
Offering myself to help maintain:

```suggestion
  - codificat
  - goern
  - fridex
  - mayacostantini
```

2022-05-11 08:22 UTC, codificat commented on .aicoe-ci.yaml
> ----
I would leave that comment there, it doesn't hurt to point to docs

2022-05-11 08:40 UTC, mayaCostantini commented
Thanks @codificat for the suggestions :100: Do you also want to be a reviewer of this repo? 
And @thoth-station/devs you are welcome to add or remove yourself from the maintainers/approvers list :+1:

2022-05-11 10:36 UTC, codificat requested changes
One more thing about removing `maintainers` from `.thoth.yaml` (relying on OWNERS instead)

2022-05-11 10:36 UTC, codificat commented on .thoth.yaml
> +      maintainers:
I forgot to mention this before: let's remove the `maintainers` section from `.thoth.yaml`, as this repo already has an OWNERS file and Kebechet will take that list from the `approvers` in that file - so, removing this section from here avoids redundancy and potential inconsistencies

2022-05-11 16:04 UTC, mayaCostantini commented
@codificat Ready for review :+1:

2022-05-12 07:30 UTC, codificat commented
Thanks,
/lgtm

2022-05-12 07:32 UTC, mayaCostantini commented
Merging as discussed with @codificat

2022-05-12 07:32 UTC, merged